// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0LwL920p4HpInhmDrvs9M9gD5SoxzUc',
    appId: '1:227541948716:web:2b4468734952bdc1e93489',
    messagingSenderId: '227541948716',
    projectId: 'comprodrone-hifah',
    authDomain: 'comprodrone-hifah.firebaseapp.com',
    storageBucket: 'comprodrone-hifah.appspot.com',
    measurementId: 'G-G7FJ6V8F45',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPSDxE8t-2XX5w5N-jy6or__VW698sMHM',
    appId: '1:227541948716:ios:b447b6550acfc124e93489',
    messagingSenderId: '227541948716',
    projectId: 'comprodrone-hifah',
    storageBucket: 'comprodrone-hifah.appspot.com',
    iosBundleId: 'com.example.comProDrone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU0LwL920p4HpInhmDrvs9M9gD5SoxzUc',
    appId: '1:227541948716:web:09b3e3fdfdc3d8d1e93489',
    messagingSenderId: '227541948716',
    projectId: 'comprodrone-hifah',
    authDomain: 'comprodrone-hifah.firebaseapp.com',
    storageBucket: 'comprodrone-hifah.appspot.com',
    measurementId: 'G-S1YMR6SBDS',
  );
}
